### ISSUE TITLE
Visual artifact remains on the screen when switching tabs

### ISSUE THREAD

**Issue by EricTran5791** [OinkIguana/conartist#3]
Replication steps:
1. Go to a convention page
2. Start switching tabs
3. Notice that there is a visual artifact on the left side of the screen that covers the tab contents

I'm using the web app on the latest Chrome on Windows.

![image](https://user-images.githubusercontent.com/6274717/32028547-2d6b92e2-b9bd-11e7-9887-7cd2f9665259.png)

**Comment by OinkIguana** [comment]
Seems this does not occur on Ubuntu Chrome. Only seen it on Windows Chrome so far.
